docs(css-modules): replace postcss-scss (#6828)
* docs(css-modules): replace postcss-scss

👋 Hey, just started a fresh gatsby project and was trying to use css-modules from `.scss` files. 
Unfortunately, I wasn't able to get this working with the `postcss-scss` as originally suggested. 
Stumbled on a [blog](https://medium.com/@PostgradExpat/using-gatsby-with-css-modules-and-scss-7e75a05533a4) that suggested using `gatsby-plugin-sass` and this worked for me right away. 

When trying to use `postcss-scss` with the filename as `filename.module.scss` or `filename.scss`, I get the following compile error in my terminal: 

```bash
 ERROR  Failed to compile with 1 errors                               22:00:20

 error  in ./src/components/HomePage/index.module.scss

Module parse failed: /Users/brianhan/dev/brianhan.co/src/components/HomePage/index.module.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/brianhan/dev/brianhan.co/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/brianhan/dev/brianhan.co/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/brianhan/dev/brianhan.co/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)

 @ ./src/components/HomePage/index.jsx 10:19-49 17:2-19:4 18:4-34
```

Maybe I'm missing a step with using `postcss-scss` but just thought it might be helpful to switch the docs over to suggesting `gatsby-plugin-sass` since this worked for me right out of the box.

* Add disclaimer

* Revert back to original docs about postcss-scss

* Delete whitespace to avoid unneeded diffs

* Add space between options and fileTypes

* Add space correctly to avoid diffs